//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KagEditor.Wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenFilePhysicalLocation {
            get {
                return ((string)(this["OpenFilePhysicalLocation"]));
            }
            set {
                this["OpenFilePhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OriginalFilePhysicalLocation {
            get {
                return ((string)(this["OriginalFilePhysicalLocation"]));
            }
            set {
                this["OriginalFilePhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CountFolderPhysicalLocation {
            get {
                return ((string)(this["CountFolderPhysicalLocation"]));
            }
            set {
                this["CountFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranslatedFolderPhysicalLocation {
            get {
                return ((string)(this["TranslatedFolderPhysicalLocation"]));
            }
            set {
                this["TranslatedFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OriginalFolderPhysicalLocation {
            get {
                return ((string)(this["OriginalFolderPhysicalLocation"]));
            }
            set {
                this["OriginalFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RescriptedFolderPhysicalLocation {
            get {
                return ((string)(this["RescriptedFolderPhysicalLocation"]));
            }
            set {
                this["RescriptedFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepackFolderPhysicalLocation {
            get {
                return ((string)(this["RepackFolderPhysicalLocation"]));
            }
            set {
                this["RepackFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepackFilePhysicalLocation {
            get {
                return ((string)(this["RepackFilePhysicalLocation"]));
            }
            set {
                this["RepackFilePhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ToTranslateFolderPhysicalLocation {
            get {
                return ((string)(this["ToTranslateFolderPhysicalLocation"]));
            }
            set {
                this["ToTranslateFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RetranslatedFolderPhysicalLocation {
            get {
                return ((string)(this["RetranslatedFolderPhysicalLocation"]));
            }
            set {
                this["RetranslatedFolderPhysicalLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CleanedFolderPhysicalLocation {
            get {
                return ((string)(this["CleanedFolderPhysicalLocation"]));
            }
            set {
                this["CleanedFolderPhysicalLocation"] = value;
            }
        }
    }
}
